using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace gui
{
    /// <summary>
    /// Interaction logic for gui.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class gui : ContentPage
    {
        public gui()
        {
            InitializeComponent();
        }
    }
}
	