using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace splash_screen_15
{
    /// <summary>
    /// Interaction logic for splash_screen_blank.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class splash_screen_blank : ContentPage
    {
        public splash_screen_blank()
        {
            InitializeComponent();
        }
    }
}
	